all:
  children:
    app_servers:
      hosts:
        app:
          ansible_host: "{{ lookup('env', 'APP_PUBLIC_IP') }}"
          ansible_user: opc
          ansible_ssh_private_key_file: "{{ lookup('env', 'SSH_PRIVATE_KEY_PATH') }}"
    nginx_servers:
      hosts:
        nginx:
          ansible_host: "{{ lookup('env', 'NGINX_PUBLIC_IP') }}"
          ansible_user: opc
          ansible_ssh_private_key_file: "{{ lookup('env', 'SSH_PRIVATE_KEY_PATH') }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
